name: Get Followers with Names

on:
  schedule:
    - cron: '*/20 * * * *' # Каждые 20 минут
  workflow_dispatch: # Кнопка ручного запуска

jobs:
  update-followers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Followers List
        uses: subhamx/github-followers-badge@v1.0.10
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Параметры отображения: выводим аватар и имя
          with_avatar: true
          with_name: true
          # Количество человек в одной строке таблицы
          per_row: 5
          # Максимальное количество отображаемых людей всего
          max_followers: 25

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          git add -A
          git commit -m "Update followers list" || exit 0
          # Подтягиваем изменения, чтобы не было конфликтов (замените main на master, если нужно)
          git pull --rebase origin main
          git push origin main
